CREATE TABLE clients (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    name VARCHAR(255) UNIQUE NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    phone_number VARCHAR(30) UNIQUE NOT NULL,
    company_code VARCHAR(50) UNIQUE NOT NULL, -- like FASTSHIP
    subscription_plan VARCHAR(50),
    logo_url TEXT UNIQUE NOT NULL,
    is_active BOOLEAN DEFAULT TRUE,
    street_address VARCHAR(255) UNIQUE NOT NULL,
    city VARCHAR(100) UNIQUE NOT NULL,
    state VARCHAR(100) UNIQUE NOT NULL,
    postal_code VARCHAR(20) UNIQUE NOT NULL,
    country VARCHAR(100) UNIQUE NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
